firmware-nxp-wifi: Keep old file name of nxp8997 and nxp9098
Latest recipe from meta-freescale has upgraded to NXP SDK 6.52-2.2.0
and these files are renamed in the new firmware, however, for Variscite
we still use a fork of 6.1.36 SDK and we need to keep the old names packaged
as well.

Fixes

ERROR: firmware-nxp-wifi-1.0-r0 do_package: QA Issue: firmware-nxp-wifi: Files/directories were installed but not shipped in any package:

/usr/lib/firmware/nxp/uartuart8997_bt_v4.bin
/usr/lib/firmware/nxp/uartuart9098_bt_v1.bin

Signed-off-by: Khem Raj <raj.khem@gmail.com>